### ISSUE TITLE
injecting props into a reuse component..

### ISSUE THREAD

**Issue by DavidSanwald** [diegohaz/reuse#12]
Probably it's not even a reuse issue but my undeveloped understanding of some of the general logic behind it:
If I want to use, for example, a hook, that takes a reuse/styled-components element as an argument and injects some event handler via clone.children into the element, it does not work with reuse.
What's the missing piece of the puzzle? (:

**Comment by DavidSanwald** [comment]
https://codesandbox.io/embed/reusestyledcomponents-w0bk0?fontsize=14

here's a minimal example. most likely the mistake is on my side.

**Comment by diegohaz** [comment]
Hi David. Thank you for the reproduction.

Well, indeed, it's not a Reuse issue. I'm not sure exactly what you want to do there. But here's a working version of your code: https://codesandbox.io/s/reusestyledcomponents-zpw9i

Nonetheless, I suggest you to take a look into some existing `useHover` or similar implementations out there. You may find something better.
