### ISSUE TITLE
Question: Advantages/disadvantages compared to other approaches?

### ISSUE THREAD

**Issue by jazen** [diegohaz/reuse#2]
Could you please elaborate on how your approach differs from using render props and/or higher-order components?

**Comment by diegohaz** [comment]
Hey, @jazen. Thanks for bringing this up.

**Render props**
```jsx
<Paper>
  {paperProps => (
    <Rounded {...paperProps}>
      {roundedProps => (
        <Button {...roundedProps}>
          {buttonProps => (
            <button {...buttonProps}>Button</button>
          )}
        </Button>
      )}
    </Rounded>
  )}
</Paper>
```

**High-order components**
```jsx
withPaper(withRounded(withButton(props => <button {...props}>Button</button>)));
```

**Reuse**
```jsx
use(Paper, Rounded, Button);
// or
<Paper use={[Rounded, Button]} />
```

When using render props or hocs, you have to stick with their static (hocs) or dynamic implementation (render props). With Reuse, besides simplicity, you can use both depending on your needs.

If people find this useful, we can write a more detailed comparison in readme.

**Comment by jazen** [comment]
@diegohaz Thanks for the quick answer—and yeah, I guess this question will come up again, so I'll leave a vote on your comment.

**Comment by sonhanguyen** [comment]
one disadvantage is that the component tree becomes pretty bloated with heavily composed elements, so it's a little annoying on debugging. Everewhere `PaperRoundedButton` is used there are 3 levels of nesting.

My suggestion is if you can provide special optimization for when all the components to be composed are `SFC`, which is most of the "styling components", then you can just call the functions directly.
