### ISSUE TITLE
styles composition with styled-components@4

### ISSUE THREAD

**Issue by brabeji** [diegohaz/reuse#6]
Hello @diegohaz!

I've realized that contrary to my first impression, `reuse` is not aware of `styled-components@4` component extension feature. That makes predictable overriding of styles impossible, as the order of generated classes depends on component declaration/import order.

This might be out of scope for `reuse` if CSS properties of combined components are considered disjunct by convention, which might be a good idea.

I still see a lot of potential in this so I took a quick hack at that here [https://github.com/brabeji/styled-compose](https://github.com/brabeji/styled-compose)

What do you think?

**Comment by diegohaz** [comment]
Awesome solution, @brabeji. 

I'll be looking forward to seeing where it goes. Keep the good work.
