### ISSUE TITLE
Babel plugin for reuse?

### ISSUE THREAD

**Issue by IniZio** [diegohaz/reuse#9]
I think having a babel plugin will make using this library even more silky smooth, like

```json
"plugins": [
  ["babel-plugin-reuse", [{
    "prop": "as"
  }]]
]
```

That way even primitives like `h1` can use reuse right in jsx like

```jsx
<h1 as={Heading}/>
```

I am trying to make it, though I don't know much about making babel plugins :thinking:

**Comment by IniZio** [comment]
Making the attempt at https://github.com/IniZio/babel-plugin-reuse/

**Comment by diegohaz** [comment]
That's a really good idea. But I think `<h1 use={Heading} />` should translate to `<use(Heading, "h1") />`, right?

**Comment by IniZio** [comment]
Ar yea just scribbled the readme didn't notice that :joy:

**Comment by IniZio** [comment]
Currently it strips the `use` prop and gets the prop value, still figuring out how to swap out the component though :thinking:
